require("base/key")
require("base/core")
require("plugins")
require("setup/telescope-config")
require("setup/treesitter-config")
require("setup/colorscheme")
require("setup/duyneed-config")
require("setup/buffer-config")
require("setup/autopair-config")
require("setup/lualine-config")
require("setup/nvimcmp-config")
require("setup/nvimlsp-config")
require("setup/nonelsp-config")
vim.cmd [[colorscheme solarized-osaka]]
